// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
// / await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt2dLXdWZfAslqnq8AzD-ZaqKyMDhmWV0',
    appId: '1:1037081931118:web:d4115ce2e0b5c9245ba57f',
    messagingSenderId: '1037081931118',
    projectId: 'sustainify-91e90',
    authDomain: 'sustainify-91e90.firebaseapp.com',
    storageBucket: 'sustainify-91e90.appspot.com',
    measurementId: 'G-P8QZ546XYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh-6e0WWyKJaN7SkiudJ2LuJ8r68DveFU',
    appId: '1:1037081931118:android:3a3aa6ac6ee4a12b5ba57f',
    messagingSenderId: '1037081931118',
    projectId: 'sustainify-91e90',
    storageBucket: 'sustainify-91e90.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi5yEanPOlMQXgCfw8Xf0ZfLxtaPT5s74',
    appId: '1:1037081931118:ios:669978ddb7e232335ba57f',
    messagingSenderId: '1037081931118',
    projectId: 'sustainify-91e90',
    storageBucket: 'sustainify-91e90.appspot.com',
    iosBundleId: 'com.example.socialCode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi5yEanPOlMQXgCfw8Xf0ZfLxtaPT5s74',
    appId: '1:1037081931118:ios:92165dbb192a03395ba57f',
    messagingSenderId: '1037081931118',
    projectId: 'sustainify-91e90',
    storageBucket: 'sustainify-91e90.appspot.com',
    iosBundleId: 'com.example.socialCode.RunnerTests',
  );
}
